# Dependabot configuration for automatic dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "dependency-update"
    # Group related updates together
    groups:
      build-info:
        patterns:
          - "org.jfrog.buildinfo:*"
      atlassian:
        patterns:
          - "com.atlassian.*:*"
      jackson:
        patterns:
          - "com.fasterxml.jackson.*:*"
      apache:
        patterns:
          - "org.apache.*:*"
      logging:
        patterns:
          - "*slf4j*"
          - "*log4j*"
          - "*reload4j*"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore specific dependencies that require manual updates
    ignore:
      # Ignore major version updates for these core dependencies
      - dependency-name: "com.atlassian.bamboo:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jfrog.buildinfo:*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"